In [1]:
import numpy as np

def solve_linear_equation(A, b):
   # enter your code here, and remove the following line (30%)
   # 1. calculate the rank (check if rank(A) == rank([A b]))
   rank_A = np.linalg.matrix_rank(A)  # directly pass A to call the method
   matrix_Ab = np.hstack((A, b))  # stack b as the last column of A
   rank_Ab = np.linalg.matrix_rank(matrix_Ab)  
   if rank_A != rank_Ab:
     return -1
   else:  # consistent
     # check if rank(A) == number of columns of A
     if rank_A == A.shape[1]:  # full rank
       return 1
     else:
       return 0 # infinite solutions

def flag_to_message(flag):
   if flag == 1:
     print('The linear system Ax=b has only one solution.')
   elif flag == 0:
     print('The linear system Ax=b has infinitely many solutions.')
   elif flag == -1:
     print('The linear system Ax=b has no solutions.')
   else:
     print('Unknown flag!')

def get_input_data(input_id):
   if input_id == 'case1': 
     A = np.array([[3, 2, -1], [6, -1, 3], [1, 10, -2]])
     b = np.array([[-7], [-4], [2]])
   elif input_id == 'case2':
     A = np.array([[4, -1, 3], [21, -4, 18], [-9, 1, -9]])
     b = np.array([[5], [7], [-8]])
   elif input_id == 'case3':
     A = np.array([[7, -4, 1], [3, 2, -1], [5, 12, -5]])
     b = np.array([[-15], [-5], [-5]])
   return A, b

if __name__ == '__main__':
   for case in ['case1', 'case2', 'case3']:
     A, b = get_input_data(case)
     print(case)
     print('A =', A, 'b =', b.T)
     flag = solve_linear_equation(A, b)
     flag_to_message(flag)
     if flag == 1:
       print('The solution is ', np.linalg.solve(A, b))
     print()


case1
A = [[ 3  2 -1]
 [ 6 -1  3]
 [ 1 10 -2]] b = [[-7 -4  2]]
The linear system Ax=b has only one solution.
The solution is  [[-2.]
 [ 1.]
 [ 3.]]

case2
A = [[ 4 -1  3]
 [21 -4 18]
 [-9  1 -9]] b = [[ 5  7 -8]]
The linear system Ax=b has no solutions.

case3
A = [[ 7 -4  1]
 [ 3  2 -1]
 [ 5 12 -5]] b = [[-15  -5  -5]]
The linear system Ax=b has infinitely many solutions.



In [2]:
# Can we use np.linalg.solve() to determine whether 𝐀𝐱=𝐛 is consistent? Explain the reason for your answer. (5%)
# Write down your answer here.

# Answers:
# 不行，consistent包含"恰有一組解"跟"無限多組解"兩種情況，
# 而np.linalg.solve()只能解出"恰有一組解"的情況，無法判斷是否有無限多組解。

In [3]:
# Given matrix 𝐀 of dimension (m,n). If rank(𝐀)=𝑛, can we infer that 𝐀𝐱=𝐛 is consistent? Explain the reason for your answer. (5%)
# Write down your answer here.

# Answers:
# 不行，可以舉反例說明，例如有一個3x2的矩陣A，rank(A) = 2，但是rank([A b]) = 3，得到無解的情況。
# 例如: 
# [ 1 4 | 3 ]    [ 1  4 |  3 ]   [ 1  4 |  3 ]
# [ 2 7 | 5 ]  = [ 0 -1 | -1 ] = [ 0 -1 | -1 ] 
# [ 1 9 | 1 ]    [ 0  5 | -2 ]   [ 0  0 | -7 ]